<?php
// $Id$
/**
 * @file
 * Email the specified contents of a page
 */

use TijsVerkoyen\CssToInlineStyles\CssToInlineStyles;

/**
 * Implements hook_block_info().
 */
function email_page_block_info() {
  $blocks['email_page'] = array(
    'info' => t('Email Page'),
    'status' => FALSE,
    'visibility' => 0,
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function email_page_block_configure($delta = '') {
  $form = array();
  if ($delta == 'email_page') {
    $before = variable_get('email_page_default_before', array(
      'value' => '',
      'format' => NULL
    ));
    $after = variable_get('email_page_default_after', array(
      'value' => '',
      'format' => NULL
    ));
    $form['email_page'] = array(
      '#type' => 'fieldset',
      '#title' => t('Email Page Settings'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $form['email_page']['email_page_config_description'] = array(
      '#markup' => '<p>Specify defaults to use for the email page block.</p><p>All fields work with tokens.</p>',
    );
    if (module_exists('token')) {
      $form['email_page']['token_tree'] = array(
        '#theme' => 'token_tree_link',
        '#token_types' => array('user'),
      );
    }
    else {
      $form['email_page']['token_tree'] = array(
        '#markup' => '<p>' . t('Enable the <a href="@drupal-token">Token module</a> to view the available token browser.', array('@drupal-token' => 'http://drupal.org/project/token')) . '</p>',
      );
    }
    $form['email_page']['email_page_scrape_element'] = array(
      '#type' => 'textfield',
      '#title' => t('Element to scrape'),
      '#description' => t('Use a class or ID to specify the HTML element that the Ajax will scrape to get content for the email.'),
      '#required' => TRUE,
      '#default_value' => variable_get('email_page_scrape_element', '.region-content'),
    );
    $form['email_page']['email_page_default_draft_to'] = array(
      '#type' => 'emailfield',
      '#title' => t('Draft version recipient email'),
      '#description' => t('Draft emails will be sent to this address.'),
      '#required' => FALSE,
      '#placeholder' => 'email@example.com',
      '#default_value' => variable_get('email_page_default_draft_to', ''),
    );
    $form['email_page']['email_page_default_final_to'] = array(
      '#type' => 'emailfield',
      '#title' => t('Final version recipient email'),
      '#description' => t('Final emails will be sent to this address.'),
      '#required' => FALSE,
      '#placeholder' => 'email@example.com',
      '#default_value' => variable_get('email_page_default_final_to', ''),
    );
    $form['email_page']['email_page_default_subject'] = array(
      '#type' => 'textfield',
      '#title' => t('Subject'),
      '#description' => t('This will be the subject of the email'),
      '#required' => TRUE,
      '#default_value' => variable_get('email_page_default_subject', ''),
    );
    $form['email_page']['email_page_default_before'] = array(
      '#type' => 'text_format',
      '#title' => t('Text to place above content'),
      '#default_value' => $before['value'],
      '#format' => $before['format'],
      '#rows' => 10,
    );
    $form['email_page']['email_page_default_after'] = array(
      '#type' => 'text_format',
      '#title' => t('Text to place after content'),
      '#default_value' => $after['value'],
      '#format' => $after['format'],
      '#rows' => 10,
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function email_page_block_save($delta = '', $edit = array()) {
  if ($delta == 'email_page') {
    variable_set('email_page_scrape_element', $edit['email_page_scrape_element']);
    variable_set('email_page_default_draft_to', $edit['email_page_default_draft_to']);
    variable_set('email_page_default_final_to', $edit['email_page_default_final_to']);
    variable_set('email_page_default_subject', $edit['email_page_default_subject']);
    variable_set('email_page_default_before', $edit['email_page_default_before']);
    variable_set('email_page_default_after', $edit['email_page_default_after']);
  }
  return;
}

/**
 * Implements hook_block_view().
 */
function email_page_block_view($delta = '') {
  $block = array();
  if ($delta == 'email_page') {
    $block['content'] = array(
      'email_page_form' => drupal_get_form('email_page_form'),
    );
  }
  return $block;
}

/**
 * Implements hook_menu().
 */
function email_page_menu() {
  $items['email_page'] = array(
    'page callback' => 'email_page_process',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'email_page_response',
  );
  return $items;
}

/**
 * Returns the form to email the current page
 *
 * @return array
 */
function email_page_form() {
  global $user;
  $token_entities = array(
    'user' => $user,
  );
  $key = 'draft';
  $to = token_replace(variable_get('email_page_default_draft_to', ''), $token_entities);
  $form['#action'] = url('email-page');
  $form['email_page_key'] = array(
    '#type' => 'radios',
    '#title' => t('Type of email'),
    '#description' => t('Draft emails will have "DRAFT: " appended before the subject.'),
    '#default_value' => $key,
    '#options' => array(
      'draft' => t('Draft'),
      'final' => t('Final')
    ),
    '#ajax' => array(
      'callback' => 'email_page_type_ajax_callback',
      'wrapper' => 'email-page-to-wrapper',
    ),
  );
  $form['email_page_to'] = array(
    '#type' => 'emailfield',
    '#title' => t('To'),
    '#description' => t('The content will be emailed to this address.'),
    '#required' => TRUE,
    '#default_value' => $to,
    '#placeholder' => 'email@example.com',
    '#prefix' => '<div id="email-page-to-wrapper">',
    '#suffix' => '</div>',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  return $form;
}

/**
 * Ajax callback for email type selector in tab form
 *
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function email_page_type_ajax_callback($form, &$form_state) {
  $key = $form_state['input']['email_page_key'];
  $form['email_page_to']['#value'] = variable_get('email_page_default_' . $key . '_to', '');
  return $form['email_page_to'];
}

/**
 * Submission handler for tab form
 *
 * @param $form
 * @param $form_state
 */
function email_page_form_submit($form, &$form_state) {
  if (!isset($form_state['storage']['confirm'])) {
    $form_state['storage']['confirm'] = TRUE;
    $form_state['rebuild'] = TRUE;
    $_SESSION['email_page_original_values'] = $form_state['values'];
  }
  else {
    try {
      $stored = $_SESSION['email_page_original_values'];
      if ($node = node_load($stored['email_page_nid'])) {
        global $user;
        $token_entities = array(
          'user' => $user,
          'node' => $node,
        );
        $before = token_replace(check_markup(
          $stored['email_page_before']['value'],
          $stored['email_page_before']['format']
        ), $token_entities);
        $after = token_replace(check_markup(
          $stored['email_page_after']['value'],
          $stored['email_page_after']['format']
        ), $token_entities);
        $email_render_array = array(
          'before' => array(
            '#markup' => $before,
          ),
          'content' => node_view($node),
          'after' => array(
            '#markup' => $after,
          ),
        );
        $email_rendered = render($email_render_array);
        $email_content = _email_page_inline_css($email_rendered);
        drupal_mail(
          'email_page',
          $stored['email_page_key'],
          $stored['email_page_to'],
          language_default(),
          array(
            'subject' => $stored['email_page_subject'],
            'body' => $email_content,
          )
        );
      }
      else {
        throw new Exception('The content could not be loaded.');
      }
      unset($_SESSION['email_page_original_values']);
      drupal_set_message(t('The email has been sent.'));
    }
    catch (Exception $e) {
      drupal_set_message(t($e->getMessage()), 'error');
    }
  }
}

/**
 * Implements hook_mail().
 */
function email_page_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
  switch ($key) {
    case 'draft':
      $message['subject'] = 'DRAFT: ' . $params['subject'];
      break;

    case 'final':
      $message['subject'] = $params['subject'];
      break;
  }
  $message['body'][] = $params['body'];
}

/**
 * Ports CSS from email_page.css into a form usable by email clients
 *
 * @param $html
 *
 * @return string
 * @throws \TijsVerkoyen\CssToInlineStyles\Exception
 */
function _email_page_inline_css($html) {
  try {
    $cssToInlineStyles = new CssToInlineStyles();
    $css_file_path = drupal_get_path('module', 'email_page') . '/email_page.css';
    $css = file_get_contents($css_file_path);
    $cssToInlineStyles->setHTML($html);
    $cssToInlineStyles->setCSS($css);
    return $cssToInlineStyles->convert();
  }
  catch (\TijsVerkoyen\CssToInlineStyles\Exception $e) {
    drupal_set_message(t('Email Node CSS could not be converted: '
      . $e->getMessage()), 'error');
  }
}
